---
title: "Effect of severe weather events in the US"
author: "Alberto Jaimes"
date: "January 2018"
output: html_document
---

```{r setup, include = FALSE, messsage = FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
library(R.utils)   # function to unzip data
library(tidyverse) # useful packages for data science
library(janitor)   # clean variable names
```

### Introduction  

### Sypnosis  

### Data loading  

First download the Storm data in the current directory.

```{r data_gathering}
url_nooa <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
path_compressed   <- "Storm_data.csv.bz2"
path_uncompressed <- "Storm_data.csv"
# download data if they are not in the working directory, and uncompress it
if (!file.exists(path_compressed)) {
  download.file(url = url_nooa, destfile = path_compressed)
  R.utils::bunzip2(path_compressed, destname = path_uncompressed, remove = FALSE)
}
# unziping
```
```{r data_reading}
storm_raw <- readr::read_csv(path_uncompressed) %>% clean_names()
```
```{r cleansing}
# select useful variables
storm_raw %>% select()
```


### Data Processing  

### Results  

### Across the U.S., which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?  

### Across the U.S, which types of events have the greatest economic consequences?

### Conclusion  

### Session info  

```{r session_info}
devtools::session_info()
```


