---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
--- 


## Loading and preprocessing the data

```{r confi, message = FALSE}
library(tidyverse)
library(knitr)
library(lubridate)
# shown code, and cache results the default
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```
```{r load}
# read_csv can read zip files
data_raw <- read_csv("activity.zip")
```

## What is mean total number of steps taken per day?

```{r viz_steps_day}
# first get total steps by date, then average them by weekday
steps_day_mean <- data_raw %>% 
  count(date, wt = steps) %>%
  mutate(day = wday(date, label = TRUE, abbr = F)) %>% 
  group_by(day) %>% summarise(mean_day = mean(n, na.rm = TRUE))
# barplot of the mean of the total steps taken each day
ggplot(steps_day_mean, aes(day, mean_day)) +
  geom_bar(stat = "identity", fill = "forestgreen") +
  labs(x = "Day of the week", y = "Steps", 
       title = "Mean of steps taken per day")
  
```


## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
